# Generated by Django 5.0 on 2024-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0002_project_service_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
