# Generated by Django 5.0 on 2024-06-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0003_alter_project_icon_alter_service_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personelknowledge',
            name='experience_year',
        ),
        migrations.RemoveField(
            model_name='personelknowledge',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='personelknowledge',
            name='total_project',
        ),
        migrations.AddField(
            model_name='personelknowledge',
            name='first_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='personelknowledge',
            name='last_name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='personelknowledge',
            name='profession',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
