# Generated by Django 5.0 on 2024-06-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0004_remove_personelknowledge_experience_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personelknowledge',
            name='definition',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
