# Generated by Django 5.0 on 2024-06-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0005_personelknowledge_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='personelknowledge',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
