# Generated by Django 5.0 on 2024-06-19 15:04

import personel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0006_personelknowledge_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personelknowledge',
            name='photo',
            field=models.ImageField(null=True, upload_to=personel.models.hero_directory_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='icon',
            field=models.ImageField(null=True, upload_to=personel.models.proje_directory_path),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(null=True, upload_to=personel.models.service_directory_path),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.ImageField(null=True, upload_to=personel.models.skill_directory_path),
        ),
    ]
