# Generated by Django 5.0 on 2024-06-19 15:35

import personel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0007_alter_personelknowledge_photo_alter_project_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to=personel.models.proje_directory_path)),
                ('name', models.CharField(max_length=25, null=True, unique=True)),
                ('definition', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
