# Generated by Django 5.0 on 2024-06-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0008_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='link',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
