# Generated by Django 5.0 on 2024-06-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0009_socialmedia_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='personelknowledge',
            name='cv',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
