# Generated by Django 5.0 on 2024-06-19 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personel', '0010_personelknowledge_cv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='icon',
            new_name='photo',
        ),
    ]
